### ISSUE TITLE
Failing tests of one-sided operations in Nasty-MPI test configuration

### ISSUE THREAD

**Issue by fmoessbauer** [dash-project/dash#181]
NastyMPI builds show that CopyTest.AsyncLocalToGlobPtr contains race conditions.

Hence, if running with NastyMPI, the tests fails because the calculated values are not correct.
See [this CI run](https://circleci.com/gh/dash-project/dash/588) for details.

@rkowalewski proofed that the test also fails if running on projekt03 when using NastyMPI. On CI this holds for all mpi environments.

**Comment by fuchsto** [comment]
@dash-project/developers 
Bumping this issue to the whole team to raise awareness for the awesomeness of [NastyMPI](https://link.springer.com/chapter/10.1007/978-3-319-43659-3_4). Use it!

This bug report is great news for the significance of QA procedures in DASH.

@fmoessbauer This is just an issue description and not your PhD thesis (yet), but: NastyMPI doesn't conduct a proof in strict formal terms.

**Comment by fuchsto** [comment]
@fmoessbauer @rkowalewski 
My first debugging attempts raised some questions regarding NastyMPI semantics and build configuration.
See my recent comment in #52 ([direct link](/dash-project/dash/issues/52#issuecomment-264604617))

**Comment by fuchsto** [comment]
Well, hm, I'm not too sure about this, there might also be a bug in Nasty-MPI perhaps?

@rkowalewski
Even some of the most basic tests fail with Nasty-MPI.
I enabled debug logging for NastyMPI and don't see anything wrong about the MPI operations executed by DART.
This is a log snippet from test case `DARTOnesidedTest.GetBlockingSingleBlock`, executed on projekt03 with:

~~~bash
LD_PRELOAD=~/opt/nasty-mpi-dbg/lib/libnasty_mpi.so \
    mpirun -n 2 ./bin/dash-test-mpi --gtest_filter="DARTOnesidedTest.GetBlockingSingleBlock"
~~~

![nastympi-log-snippet](https://cloud.githubusercontent.com/assets/37075/20856770/14c23b0c-b918-11e6-97dc-2d25121d874f.PNG)

(Also, I added coloring log messages by unit, isn't it pretty?)

Does that look right to you? DASH has been configured with `-DENABLE_SHARED_WINDOWS=OFF`.

**Comment by rkowalewski** [comment]
@fuchsto There was a small bug in Nasty-MPI where the splitting of one-sided Put/Get-Operations resulted in wrong displacement units at the target memory location. I have fixed this and pushed to the master branch in our Nasty-MPI repository. The following test works now without any errors:

~~~bash
LD_PRELOAD=~/opt/nasty-mpi-dbg/lib/libnasty_mpi.so \
    mpirun -n 2 ./bin/dash-test-mpi --gtest_filter="DARTOnesidedTest.GetBlockingSingleBlock"
~~~

Regarding the memory semantics, Nasty-MPI always assumes the unified memory model. Actually, simulating the separate model is not possible without intercepting all the low-level memory operations (e.g. malloc, memcpy,...).

**Comment by fmoessbauer** [comment]
Looks good now. However the CI does not pass as "TeamTest.Deallocate" segfaults at least [on Travis](https://travis-ci.org/dash-project/dash/builds/181408074)

**Comment by rkowalewski** [comment]
Well, this bug is a different story and I do not know if this is really new. The problem is a "double free" of `dash::Array`. In `TeamTest.Deallocate` we first call `dash::Team::free` which in turn calls `dash::Array::deallocate` (due to the registered deallocator). Then the `dash::Array` instance goes out of scope which triggers again `dass::Array::deallocate`.
I have a fix in the branch. However, this is certainly not the correct way. The critical instance is the `m_globmem` member in `dash::Array` which is deleted after the first deallocation. However, the owning `dash::Array` survives. And it makes no sense to me where the global memory of an `dash::Array` does not exist (except before the first allocation). A better solution is to encapsulate `m_globmem` into a `std::shared_pointer` which takes care of the resource lifecycle.

**Comment by fuchsto** [comment]
@fmoessbauer Apart from that: See? False positives. Didn't prove nuddin.

**Comment by fuchsto** [comment]
False positives fixed in NastyMPI, closing this issue.
