### ISSUE TITLE
TeamSpec::balance_extents() only operates on 2 dimensions

### ISSUE THREAD

**Issue by ddiefenthaler** [dash-project/dash#228]
When looking at balance_extents in [TeamSpec.h](https://github.com/dash-project/dash/blob/dd42d162a1ed0e80c934efe94c8c1977d1317a6b/dash/include/dash/TeamSpec.h#L233),
I noticed that it only balanced the extents in the first two dimensions.

As I'm probably going to need this for more dimensions in the future,
I'll try to rewrite it so that it gets balanced in all dimensions. See pull request #229.

Apart from that the current algorithm doesn't seem to be ideal,
for example 144 units get balanced to 16x9 instead of 12x12.

**Comment by fuchsto** [comment]
@ddiefenthaler Yes, that is the expected behavior. Note that the balancing is constrained with hardware topology domain sizes.
For example, with 4 sockets and 2 NUMA domains in the hardware topology, the algorithm optimizes surface-to-volume ratio by balancing extents constrained to even multiples of 8.

**Comment by ddiefenthaler** [comment]
Those constraints are interesting.
I'm quite sure that balance_extents in the current development branch does not consider any topology information. (Current implementation: [TeamSpec.h](https://github.com/dash-project/dash/blob/dd42d162a1ed0e80c934efe94c8c1977d1317a6b/dash/include/dash/TeamSpec.h#L233))
Another example, the first one might be poorly chosen: 225 units get balanced to 9x25 instead of 15x15.

**Comment by fuchsto** [comment]
Addressed in #229
