### ISSUE TITLE
DART locality subsystem initialized multiple times when thread support is disabled

### ISSUE THREAD

**Issue by fuchsto** [dash-project/dash#320]
See logs attached.

[test.nothreads.txt](https://github.com/dash-project/dash/files/838088/test.nothreads.txt)
[test.threads.txt](https://github.com/dash-project/dash/files/838087/test.threads.txt)

**Comment by devreal** [comment]
There are tons of calls to `dart__base__locality__domain__create_module_subdomains` in the logs for the `nothread` version but I have no idea where they come from atm. There are also not many places where `DASH_ENABLE_THREADSUPPORT` or `DART_ENABLE_THREADSUPPORT` are used to change the control flow and none of them seem significant. I will try to reproduce this locally.

**Comment by fuchsto** [comment]
I'm puzzled just the same. All I can tell is that with `DART_ENABLE_THREADSUPPORT=OFF` it behaves as expected, with `=ON` the log is spammed with `..._create_module_subdomains`.

**Comment by devreal** [comment]
> I'm puzzled just the same. All I can tell is that with DART_ENABLE_THREADSUPPORT=OFF it behaves as expected, with =ON the log is spammed with ..._create_module_subdomains.

From the logs you posted it looks just the other around ;)

If I run `ArrayTest.Declaration` locally on my laptop I see 21 or 27 lines with  `dart__base__locality__domain__create_module_subdomains()` in the logs but that is independent of the thread support status (I assume it has to do with the mapping from OpenMPI). Are you positive that this is related to the thread-support status?

**Comment by fuchsto** [comment]
Ah, yes, it's the other way around :)
Well, I'm positive that this is related to the `DART_ENABLE_THREADSUPPORT` option.

**Comment by devreal** [comment]
My (un-)educated guess is that the mapping is different depending on whether `MPI_Init` or `MPI_Init_threads` is called. Still, I cannot reproduce it. I guess you are using MPICH?

**Comment by devreal** [comment]
So, I kept staring at the logs you posted. The recursion really seems fishy, there are blocks with a whole bunch of calls to `dart__base__locality__domain__create_module_subdomains` without any intermediate  functions in the log. I thus assume that they are recursive calls. Understanding this monstrous >300loc function is anything but trivial though. 

There are some intermediate other functions between these blocks in the log, e.g., `dart__base__locality__domain__create_node_subdomains`. However, the function names in the trace do not match the actual function names: `dart__base__locality__domain__create_subdomains` prints as `dart__base__locality__domain__create_node_subdomains` and `dart__base__host_topology__host_domain` prints  as `dart__base__host_topology__module_units`. Not sure if there other rogues functions like that. Since I cannot reproduce it locally or on our cluster (using OpenMPI), I cannot go any further at this point. Can you please fix the debug output and re-run? 

I also noticed that your PAPI integration is broken (see beginning of the log), not sure whether that has any impact though.

**Comment by fuchsto** [comment]
The PAPI integration itself is not broken, it just the linked PAPI library. PAPI expects that libpapi is build with the same build environment as the application it is linked.
I'm fixing the scopes in log messages (and the linked PAPI lib to be sure) and will report back with new logs.
