### ISSUE TITLE
GlobAsyncRef uses blocking dart operations

### ISSUE THREAD

**Issue by fmoessbauer** [dash-project/dash#357]
According to my understanding, `dash::GlobAsyncRef` should perform non-blocking puts and gets. However a first glance at the code this is not the case: See [GlobAsyncRef.h,L190](https://github.com/dash-project/dash/blob/development/dash/include/dash/GlobAsyncRef.h#L190).

Furthermore, the implementation does not fulfill the GlobRef concept and seems to be pretty experimental.

**Comment by fuchsto** [comment]
That's true, write-access is blocking. The reason is consistency in situations like:

~~~c++
aref = 100;
if (aref == 100) { ... }
~~~

Should be refactored and be based on `dash::Future`.

**Comment by devreal** [comment]
The implementation of `operator T()` looks broken as well: if the reference is not local, `dart_get` is called but a value is returned before any flush is performed. The `get` should be blocking to ensure consistency and no other `get` should be executed subsequently but only the locally cached value be used. I see no way `operator T()` can be truly asynchronous. 

For the assignment operator, no blocking put is necessary because the assignment caches the local value. 

Also, the `flush` method mentioned in the documentation is missing. I will work on a patch later today (hopefully).

**Comment by fuchsto** [comment]
Thanks, when patching this, see if you can make it work with `dash::Future`, perhaps as specialization.

**Comment by devreal** [comment]
Not sure what you mean with making it work with `dash::Future`. You mean `GlobAsyncRef<dash::future<T>>`?
