### ISSUE TITLE
Resolve compiler Warnings

### ISSUE THREAD

**Issue by dhinf** [dash-project/dash#367]
Resolve compiler warnings. Especially unused parameters/variables.

**Comment by ddiefenthaler** [comment]
Can you be more specific about what types of warnings and what build modes you are looking at?
Is this fixed by pull request #373? Or are there more warnings that you are looking at?

As a side note when building with a 32bit system there are some more format warnings,
as `size_type` does not match `long long unsigned int`.

**Comment by dhinf** [comment]
It is fixed with request #373. I tested my stuff and a lot unused parameters/variables warnings popped up. I fixed them in #373 . Maybe there are more. But, for now i'll close the issue.
