### ISSUE TITLE
Improve IteratorRange

### ISSUE THREAD

**Issue by fmoessbauer** [dash-project/dash#411]
While you are working on PR #410 : Please add support for the following use-cases in `dash::IteratorRange` (should be trivial):

1. Copy and move of iterators

```cpp
auto begiter = array.begin()+offset;
auto enditer = array.begin()+endoff;
return dash::make_range(begiter, enditer);
// alternative (even better)
return dash::make_range(std::move(begiter), std::move(enditer));
```

2. Random access / bracket operator if iterator provides one

```cpp
auto range = dash::make_range(begiter, enditer);
int x = range[2];
```

This will make some things so much easier, especially in the upcoming `dash::Directory`.

**Comment by fuchsto** [comment]
The first use case is already supported in #410, I am fixing some other use cases in the PR right now and hope to get it done tomorrow.

On random access / bracket operators:
The [proposed STL range concept](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4128.html#orthogonality-of-traversal-and-access-is-not-surfaced-in-the-iterator-concepts)
does not specify a bracket operator (random access / mapped lookup / ... or whatever its semantics might resolve to be) by design:

> There is no room in the hierarchy for, say, a random-access iterator that returns proxies.
> This problem is not new to ranges; however, it has serious consequnces for lazy ranges that apply
> transformations to elements on the fly. If the transformation function does not return an lvalue, the 
> range’s iterator can model no concept stronger than InputIterator, even if the resulting iterator
> could in theory allow random access.

Sure, this is just a consideration for a proposal, not a law. 

I could easily specify random access for DASH views / ranges. My current definitions for view expressions don't follow the ranges TS in places already.
These deviations are well-motivated (note the colloquial connotation, as in "but that's just my opinion, man"), but I'm a bit anxious that they could lead to broken semantics if I don't watch out. And random access looks dangerous to me in this respect.

Consider the invariant:

~~~c++
auto & ra_val = something[i];
auto & it_val = *(something.begin() + i)
assert(ra_val == it_val);
~~~

As of now, I'm not sufficiently convinced that this holds for ranges in general. Perhaps range iterators should be immutable? I'll report back on this.

P.S.:

> (should be trivial)

I feel trolled, but it's not your fault :(
