### ISSUE TITLE
Bulk wait for async copy

### ISSUE THREAD

**Issue by fmoessbauer** [dash-project/dash#416]
In the [hpccg](https://github.com/dash-project/dash-apps/blob/hpccg-coarray/hpccg/src_dash/exchange_externals.cpp#L69) benchmark the following is used to wait for a bulk of `dash::copy_async` transfers:

```c++
for(int i=0; i<num_neighbors; ++i) {
    int n_send = send_length[i];
    int neighbor = neighbors[i];
    int offset_at_neighbor = A->offset[i];
    dash::copy_async(send_buffer, send_buffer + n_send,
      narray.row(neighbor).begin() + A->offset[i]);
    send_buffer += n_send;
  }

  // wait for the transfer to complete
  narray.flush_all();
```

Is this a valid way to wait for the transfers? Otherwise I would have to use (e.g.) a `std::vector<VeryComplicatedType>` to store the futures. But as indicated, then the type of the vector might be very complicated, as `auto` cannot be used.

**Comment by rkowalewski** [comment]
"Unfortuneately" no, since the callback handle which is stored inside the returned future is not executed before `future.wait()` has been called. But I do not really understand why we cannot use auto.

While I have not tested I would expect something like this to work:
~~~cpp
using future_type = decltype(dash::copy_async(....)); //local to global as far as I can see.
std::vector<future_type> futures;

futures.push_back(dash::copy_async(...));
~~~

**Comment by devreal** [comment]
> "Unfortuneately" no, since the callback handle which is stored inside the returned future is not executed before future.wait() has been called.

That is not entirely correct: the default is to use `gptr` and call `dart_flush` in the future on them (see `DASH__ALGORITHM__COPY__USE_FLUSH` at the beginning of `Copy.h`). You can achieve the same with a single flush on the same array/matrix object instead of calling wait on each future. In case request handles are used, the picture is different as the request handles have to be waited on and free'd. 

I would like to see a a version of `dash::copy_async` that goes well without allocating a future and `std::vector`.

**Comment by rkowalewski** [comment]
Ah correct. I looked in the wrong branch (feat-192-nviews). Assuming that it can make it to development soon my explanation will be right. :)

**Comment by fmoessbauer** [comment]
Ok, thanks for the explanations. @rkowalewski yes, of course the `decltype` stuff should work, but then you have to write the copy statement in fact twice. Anyway, a bulk wait as described by @devreal seems to be the better solution.

So anyway, this should be well documented. IMO the user should not be put in charge of checking if request handles are used. Maybe this is also something for the launch / execution policies.

**Comment by rkowalewski** [comment]
> So anyway, this should be well documented. IMO the user should not be put in charge of checking if request handles are used. Maybe this is also something for the launch / execution policies.

The user does not need to be aware of request handles but the fact that  `dash::copy_async` returns a future requires to wait at least. Of course, the implementation does not bother.

>yes, of course the decltype stuff should work, but then you have to write the copy statement in fact twice.

I agree, however it is not bad style as you can find this pattern in many well-known C++ libraries. Despite the fact that It is not really comfortable. 

> Anyway, a bulk wait as described by @devreal seems to be the better solution.

In this case we have to buffer all the requests inernally in some scratchpad storage (or similar). And even then, how can we semantically apply fine-grained synchronization semantics? The user wants to synchronize only these pending copy calls.

**Comment by devreal** [comment]
> In this case we have to buffer all the requests inernally in some scratchpad storage (or similar). And even then, how can we semantically apply fine-grained synchronization semantics? The user wants to synchronize only these pending copy calls.

No you don't, that's the nice part: just initiate all the transfers and flush the segment(s) afterwards. After all, this is what the `flush` methods on the containers are there for, right? Otherwise, we should get rid of them. There is no need to internally cache them. Of course, if the user only wants to sync specific communications, then the future is the right way to go. I think these are two different concepts. 

Update: just imagine I want to communicate with 100 units and imagine that I cannot use a single `dash::copy` (the miniFE benchmark is a good example for that). That means: allocating 100 futures and 100 vectors inside them and issuing 100 calls to flush on the *same segment*.  And now tell the user that he cannot use the `flush` method on the container, because requests.

**Comment by devreal** [comment]
I've been thinking about this a bit more (while having my wisdom teeth removed...). I think there should be two options for the programmer:

1. Wait for specific asynchronous transfers via futures, which should use DART handles. It's important that the dtor of these futures releases the handles if they have not been waited upon (we'd have to add a DART function for that, which could be more robust than `MPI_Request_free` and not error out if the request is NULL or completed). This is important because a user might drop the future and wait for completion using the flush on the container. No resources should leak in that case. From a technical (MPI/DART) perspective, this is perfectly valid. 

2. Fire-and-forget asynchronous transfers. The copy initiates the transfer and the container's flush method is the only way of waiting for it to complete. While this is coarse-grain, it is more efficient (no futures, vectors, requests involved) and in some (many?) situations that's all you need.

**Comment by BenjaProg** [comment]
the call of dash::copy_async should probably look like this?
```c++
dash::copy_async(send_buffer, send_buffer + n_send,
      narray.row(neighbor).begin() + offset_at_neighbor );
```
