### ISSUE TITLE
Loop optimization breaks something?

### ISSUE THREAD

**Issue by BenjaProg** [dash-project/dash#441]
Hi all!
I think i have found a bug related to loop optimization...
A segmentation fault occurs in  [outer](https://github.com/dash-project/dash-apps/blob/master/cowichan/outer/outer.h) when the following conditions are met:

- input size with 40000
- number of units between 1-5
- program compiled in release mode (not debug mode)
- using pointer logic in both locations: [line 59 instead 57](https://github.com/dash-project/dash-apps/blob/abd0e0ea91e7d28d6c6550ddeed60f5d8fca0ef8/cowichan/outer/outer.h#L59) and [line 50 and 54 instead of line 49](https://github.com/dash-project/dash-apps/blob/abd0e0ea91e7d28d6c6550ddeed60f5d8fca0ef8/cowichan/outer/outer.h#L50)
- using intel compiler (17.0.2.174 or 18.0.0.128) [no problems with GCC 5.4.0 or GCC 7.1.0]

Only in this scenario the segmentation fault occurs.
Since it's not happing in debug mode, I can't track it down further.
But using "couts" like in [line 58](https://github.com/dash-project/dash-apps/blob/abd0e0ea91e7d28d6c6550ddeed60f5d8fca0ef8/cowichan/outer/outer.h#L58) prevents the segmentation fault. That's why i think it's probably some kind of compiler optimization.
Shared Windows doesn't seem to play a role.
(Tested on project03)

**Comment by BenjaProg** [comment]
still editing....

**Comment by devreal** [comment]
Which MPI implementation do you use? Can you try to compile in mode `RelWithDebInfo` and see if the Segfault occurs there as well? If so please post a stack trace. Otherwise, gdb can still tell you the address at which the segfault occurs, which would be interesting as well.

This might be related to #89 (alignment of memory allocated through MPI). In case you're running on an older version of Open MPI, can you try to run with Open MPI >=2.1.0?

**Comment by BenjaProg** [comment]
Were using impi/2017.2.174 and impi/2018.0.128.

I could compile DASH in Debung mode and found a way to compile my application with debug symbols as well.

Note: Default debug script in DASH isn't compiling at the moment and `RelWithDebInfo` mode isn't compiling at all for me with intel compiler.
On this machine only OpenMPI 1.10.6 is installed and i don't know how to install a new one and (!) then make DASH use it.

Now i have compiled my application with `-g -O3 -Ofast` and i now where it faults:
[In line 50](https://github.com/dash-project/dash-apps/blob/abd0e0ea91e7d28d6c6550ddeed60f5d8fca0ef8/cowichan/outer/outer.h#L50):
```
Program received signal SIGSEGV, Segmentation fault.
Outer (points=..., matOut=..., vec=..., nelts=40000) at outer.h:50
50              *matP = distance(points[gRow], points[j]);
Missing separate debuginfos, use: debuginfo-install libgcc-4.8.5-11.el7.x86_64 libstdc++-4.8.5-11.el7.x86_64
```
I just tried with mpich with no segfault, but it ran with gcc 5.4 anyway (but i couldn't load mpich and intel simultaneously)

**Comment by rkowalewski** [comment]
I have verified your example and the problem indeed manifests only with icc. However, compiling the application simply with `-O1` does not lead to a segmentation fault, suggesting that there may be some alignment issues with vectorization. So I played a little bit and found that simply changing [line 47](https://github.com/dash-project/dash-apps/blob/abd0e0ea91e7d28d6c6550ddeed60f5d8fca0ef8/cowichan/outer/outer.h#L47) to 
`for( auto j = 0; j < nelts; ++j )` 
does not lead to a segmentation fault anymore. I cannot say the exact reason (this requires more inspection of the assembly), however, be aware of the types and their length. The functions sqrt, sqr and max are all candidates for vectorization by icc.
Moreover, you are using `uint` (which is an alias to `unsigned int`) as an index type for gRow, etc. This does not match the length of the index_type in DASH (which is usually long).  Rather use the auto specifier wherever possible since the compiler usually knows better than we do.

**Comment by devreal** [comment]
> Rather use the auto specifier wherever possible since the compiler usually knows better than we do.

Cautious note here: `auto j = 0` most certainly makes `j` an `int`, irrespective of the other statements in the loop header. It's probably a good idea to explicitly make `j` long, either by using `0L` or using `index_type`/`size_t` as type.

**Comment by rkowalewski** [comment]
Right, I agree with @devreal. There are several flavors how to deal with that. I would use `auto`  for initializing `gRow` and `decltype(gRow) j = 0` in the for loop.

**Comment by rkowalewski** [comment]
I have uploaded a possible fix with minor changes.

**Comment by dhinf** [comment]
since c++11 auto i = 0 should be long long int
http://en.cppreference.com/w/cpp/language/integer_literal

**Comment by devreal** [comment]
> since c++11 auto i = 0 should be long long int

Where do you see that? Above the table is the following statement:

> The type of the integer literal is *the first type in which the value can fit*, from the list of types which depends on which numeric base and which integer-suffix was used. 

I think what is new in C++11 is that `long long int` is now an option but it's not the default. And `0` fits well into `int` :)

**Comment by dhinf** [comment]
> depends on which numeric base and which integer-suffix

0 is decimal base and no suffix -> long long int

**Comment by devreal** [comment]
> 0 is decimal base and no suffix -> long long int

The order of types checked for the value to fit is `int` -> `long int` -> `long long int` (the last is included since C++11). So, there is no reason the compiler should assume `0` to be `long long int` as it fits well into `int`.

**Comment by BenjaProg** [comment]
Big **Thanks** @rkowalewski and @devreal !!!!
i can confirm it's working :-) clean up and speed comparison is incoming!

**Comment by devreal** [comment]
Kudos to @rkowalewski for figuring out it's related to the variable types.

**Comment by BenjaProg** [comment]
Comparison between the old implementation and the new one with pointers.
measured with the following matrix sizes: 100, 400, 4000 and 40000.
[tests.zip](https://github.com/dash-project/dash/files/1322388/tests.zip)
