### ISSUE TITLE
Conceptual Problems in Pattern & Memory

### ISSUE THREAD

**Issue by fmoessbauer** [dash-project/dash#539]
During the investigation of #532 I discovered various conceptual problems:

## Pattern Related
We still have not a clear meaning what `pattern.local_capacity()` has to return:

**A: max number of local elements on any unit**
This would be beneficial, but with the current implementation it cannot be efficiently determined. Either we have to communicate the maximum number or we have to calculate the local blockspec for each unit (does not scale). AFAIK we still have not defined if the construction of a pattern is a collective operation. Hence, communication is not possible.

**B: number of allocated blocks times blocksize**
 Easy to determine but not equal for all pattern configurations, as some units might own less or no local blocks.

## Memory Related

The `GlobStaticMem` only states (according to the documentation) that the memory is static and hence cannot be resized. There is still no hint or definition if all units have to allocate the same amount of memory locally. This has caused some trouble since the beginning of DASH. Hence I recommend to make a poll on that and change the implementation accordingly. If we agree on that, we should check the actual allocation in debug mode to avoid hard to debug bugs.

In it's current version [`GlobStaticMem.local_size(unit)`](https://github.com/dash-project/dash/blob/development/dash/include/dash/memory/GlobStaticMem.h#L343) is totally broken.

## DASH vs DART Responsibility

We have to define carefully for what operations DART should be used in DASH. With the current Container + Pattern + Memory implementation, indices and coordinates are calculated multiple times for a single operation like get or even `is_local()`. I prefer to use DART whenever possible / reasonable as the overhead of the `dash::GlobPtr` and index calculations are huge.

**Comment by devreal** [comment]
> The GlobStaticMem only states (according to the documentation) that the memory is static and hence cannot be resized. There is still no hint or definition if all units have to allocate the same amount of memory locally. This has caused some trouble since the beginning of DASH. Hence I recommend to make a poll on that and change the implementation accordingly. If we agree on that, we should check the actual allocation in debug mode to avoid hard to debug bugs.

There is an item somewhere on my TODO list to extend the DART interface to accepts a hint on whether all units allocate the same amount of memory locally as this may allow for some optimizations in the back-end (MPI specifically).

Do you suggest to enforce allocating the same amount of memory on each unit even on units that have less elements? 

> In it's current version GlobStaticMem.local_size(unit) is totally broken.

Good catch (and another sad one)!

**Comment by ddiefenthaler** [comment]
First, sorry for leaving you alone with the bug yesterday...
I probably would have dived deep into other conceptual problems without finding this issue...

>We still have not a clear meaning what `pattern.local_capacity()` has to return:
>
>**A: max number of local elements on any unit**
This would be beneficial, but with the current implementation it cannot be efficiently determined. Either we have to communicate the maximum number or we have to calculate the local blockspec for each unit (does not scale). AFAIK we still have not defined if the construction of a pattern is a collective operation. Hence, communication is not possible.
>
>**B: number of allocated blocks times blocksize**
 Easy to determine but not equal for all pattern configurations, as some units might own less or no local blocks.

I do not really understand the definition either. From comparison with `std::vector` for example I would say that the capacity of the current unit should be returned, similar to `local_size`. After all for a pattern that does not grow or shrink I think this should be equal `_p.local_capacity() == _p.local_size()`.
Also from my understanding the allocation of elements is in charge of the container. So I do not know how much the pattern is involved with `capacity` at all.

I do not think that a pattern should issue a collective operation. This should be possible for each unit on its own. The collective operation starts once it is assigned to a container.

But I think that the `local_size` and `local_capacity` should be computable for any unit. Therefore I would suggest to add a parameter to select the desired unit. The documentation can state that this does not scale. To get around that the user can create a `dash::Array` and store all the `local_size()`s in it. But this should not be done by the pattern itself.

Another conceptual issue I stumbled across is the call to the `pattern.memory_layout()` ([code](https://github.com/dash-project/dash/blob/59f6d1cbeac35833f096cb9625e7cc03d0ab2037/dash/include/dash/matrix/internal/MatrixRefView-inl.h#L98)). This is not documented in the concept and may not be provided by a custom pattern.

I already opened two issues #507 and #508 a while ago. These issues are ment for the refinement of the current pattern concept.

**Comment by fuchsto** [comment]
Just to add this issue to my bookmarks:
@fuchsto

**Comment by rkowalewski** [comment]
> The GlobStaticMem only states (according to the documentation) that the memory is static and hence cannot be resized. There is still no hint or definition if all units have to allocate the same amount of memory locally. This has caused some trouble since the beginning of DASH. Hence I recommend to make a poll on that and change the implementation accordingly. If we agree on that, we should check the actual allocation in debug mode to avoid hard to debug bugs.

I completely agree with you here. And the only restriction that memory is not resizeable is fine in my opinion, for the following reason.
Whether we allocate collectively or not can be addressed with an allocation policy as often discussed. #515 provides a prototypical implementation of that, discussions about the approach are of course welcome. Apart from the implementation, if we know the allocation policy we can apply further steps:
- If the allocation policy is collective I do not see any issue for another `dart_allgather` operation in the `GlobStaticMem` constructor to retrieve the local capacity of each unit. This would solve the broken `local_capacity()` issue and since it is an expensive operation with couple of barriers anyway another one does not "hurt". It is done only once in the lifetime of a global memory object.
- If the allocation policy is '"local" (or whatever term we should use here) as used with `dash::Shared`, we of course should not apply any collective operation. And it is not needed actually since only one unit contributes any capacity.
- If the allocation policy is non-collective, asymmetric or based on epochs which permit multiple asynchronous global allocations and we cannot use `GlobStaticMem` anyway for that.

`GlobStaticMem` can be additionally restricted to support only a single local capacity for all units. However, this does not satisfy the requirements of our patterns and there is also no runtime requirement in MPI which requires that. Only patterns should care about any restrictions on distribution, capacity, etc. The only purpose of `GlobStaticMem` is to provide memory for containers, similar to `malloc` and friends which assume a simple one-dimensional flat address space without any knowledge about cartesian indexes.

**Comment by fuchsto** [comment]
Exactly, but if we are about to get our hands dirty there, then we should go all the way:

Allocation has several categories.
Two of those are `dynamic` / `static` and `collective` / `independent`. 
And there are further categories like `synchronization` and `accessibility`.
All of those are independent, of course.

Well, in formal terms, a `local` allocation policy is a special case of `asymmetric` allocation.

Don't worry about patterns too much for now, the pattern concepts are in a cocoon for metamorphosis and will reappear as beautiful butterflies.

**Comment by rkowalewski** [comment]
> Don't worry about patterns too much for now, the pattern concepts are in a cocoon for metamorphosis and will reappear as beautiful butterflies.

Sounds like music in my ears and I really get appetite for that.

**Comment by fuchsto** [comment]
@rkowalewski Let's have a meeting for this, I could use another pair of eyes for this!

**Comment by rkowalewski** [comment]
@fmoessbauer  All your conceptual problems should be fixed in #515. Maybe we can talk again about this issue today?

**Comment by rkowalewski** [comment]
After discussing the original issues with @fmoessbauer we can finally close it since everything is either addressed in #515 or fixed by other pull requests.
