### ISSUE TITLE
Build v0.3.0 under macOS

### ISSUE THREAD

**Issue by nbenn** [dash-project/dash#616]
I'm encountering several fatal errors when building v0.3.0 under macOS. In case anyone is having similar problems and if you are interested in fixing this, I'm opening a PR alongside this issue.

1. undeclared identifier `HOST_NAME_MAX`: as discussed in #581
1. `malloc.h` file not found: as discussed e.g. in RIOT-OS/RIOT#2361
1. loads of errors from timing functionality, e.g.
    ```
    dash/include/dash/util/Timer.h:57:11: error:
          unknown type name 'Timestamp_t'; did you mean 'timestamp_t'?
      typedef Timestamp_t timestamp_type;
              ^~~~~~~~~~~
              timestamp_t

    dash/include/dash/util/Timer.h:83:20: error:
          member reference base type
          'dash::util::Timer<dash::util::TimeMeasure::Clock>::timestamp_t'
          (aka 'unsigned long long') is not a structure or union
        now = timestamp.Value();
              ~~~~~~~~~^~~~~~

    dash/include/dash/util/Timer.h:85:27: error:
          use of undeclared identifier 'Timestamp_t'; did you mean 'Timestamp'?
          static_cast<double>(Timestamp_t::FrequencyPrescale())) /
                              ^~~~~~~~~~~
                              Timestamp

    dash/include/dash/util/Timer.h:105:27: error:
          use of undeclared identifier 'Timestamp_t'; did you mean 'Timestamp'?
          static_cast<double>(Timestamp_t::FrequencyScaling());
                              ^~~~~~~~~~~
                              Timestamp

    dash/include/dash/util/Timer.h:145:18: error:
          no type named 'Calibrate' in 'dash::util::Timestamp'
        Timestamp_t::Calibrate(freq);
        ~~~~~~~~~~~~~^

    dash/include/dash/util/Timer.h:150:12: error:
          no member named 'TimerName' in 'dash::util::Timestamp'; did you mean simply
          'TimerName'?
        return Timestamp_t::TimerName();
               ^~~~~~~~~~~~~~~~~~~~~~
               TimerName
    ```
    I did not go ahead and try to resolve these issues, but just installed PAPI.
 1. `librt` is not available on macOS (see [here](https://stackoverflow.com/questions/1505402/library-not-found-for-lrt-with-qtcreator-mac-os) or [here](https://stackoverflow.com/questions/49268901/issue-when-linking-with-lrt-on-mac-osx)). A further reference to `librt` is [here](https://github.com/nbenn/dash/blob/18be4d8dd00d183497197c0ef54b390f92b63c49/CMakeExt/FindMKL.cmake#L184). I have no MKL available so this is not relevant for me.
1. use of undeclared identifier 'memalign': see [this](https://stackoverflow.com/questions/21048148/memalign-not-defined-in-mac-os-x).

**Comment by fmoessbauer** [comment]
See also #404

**Comment by pascalj** [comment]
Thanks for taking a shot at this! These are only minor changes that don't break anything for the non-macOS folks.

Did you run the tests successfully on macOS? I was trying on 10.14.1 with GCC 8.2, OpenMPI 3.1.3, hwloc and PAPI enabled. Without hwloc I get an error from dart "HWLOC or PAPI required if not running on a Linux platform" at runtime although PAPI was enabled. Will check that tomorrow. With hwloc it wouldn't build, because hwloc 2.0 (that brew installs) [removed the field](https://raw.githubusercontent.com/open-mpi/hwloc/v2.0/NEWS). Will also try with an older version tomorrow.

**Comment by pascalj** [comment]
I looked some more into the issues and I think it would probably be possible to make DASH compatible with macOS. However, as @fmoessbauer noted in #404 macOS is not really an HPC plattform plus we don't have a macOS CI. Therefore I'm closing this issue.

That being said: I'm happy to review and merge a PR fixing the compatibility issues if that works for you. We just can't guarantee future compatibility due to the lack of tests and users on the plattform. Feel free to reopen this ticket then.
